package com.greensoft.greentranserpnative.ui.login.models

data class UserDataModel
    (
    val appactivedate: String,
    val commandmessage: Any,
    val commandstatus: Int,
    val companyid: Int,
    val companyid1: String,
    val companytype: String,
    val compcode: String,
    val compname: String,
    val controlcode: String,
    val cscode: String,
    val currency: String,
    val custcode: Any,
    val custname: Any,
    val dashboardnewdt: String,
    val defaultbranchcode: Any,
    val defaultbranchname: Any,
    val empdeignation: String,
    val empdepartment: String,
    val empdob: String,
    val employeeid: Int,
    val empname: String,
    val executiveid: Any,
    val genablemodegroup: String,
    val ledcode: Any,
    val ledname: Any,
    val loginbranchcode: String,
    val loginbranchname: String,
    val loginbranchtype: String,
    val logindatetime: String,
    val password: String,
    val sessionid: String,
    val stncode: String,
    val stnname: String,
    val unapprovedstrs: Any,
    val usercode: String,
    val usergroupcode: String,
    val username: String
)