package com.greensoft.greentranserpnative.ui.operation.pod_entry.models

data class PodEntryModel(
    val cnge: String?,
    val cngr: String?,
    val commandmessage: Any?,
    val commandstatus: Int?,
    val createid: Any?,
    val custcode: String?,
    val custname: String?,
    val cweight: Double?,
    val destcode: String?,
    val destname: String?,
    val dlvboyname: Any?,
    val dlvdt: Any?,
    val dlvtime: Any?,
    val drsno: String?,
    val grdt: String?,
    val grno: String?,
    val name: Any?,
    val orgcode: String?,
    val origin: String?,
    val pckgs: Any?,
    val phno: Any?,
    val picktime: String?,
    val poddate: String?,
    val podimage: Any?,
    val receivedt: String?,
    val receivetime: String?,
    val relation: Any?,
    val remarks: Any?,
    val saletype: String?,
    val sign: Any?,
    val signimage: Any?,
    val stamp: Any?
)