package com.greensoft.greentranserpnative.ui.booking.models

data class CustomerSelectionModel(
    val active: String,
    val actulcustname: String,
    val address: String,
    val branchname: String,
    val city: String,
    val cngecode: String,
    val cngename: String,
    val cngrcode: String,
    val cngrname: String,
    val commandmessage: Any,
    val commandstatus: Int,
    val country: String,
    val cperson: String,
    val custcode: String,
    val custname: String,
    val customerdefaultas: String,
    val disablemanualratesingr: String,
    val emailid: String,
    val gstno: String,
    val gstverified: String,
    val ledcode: String,
    val ledname: String,
    val refcode: Any,
    val showcngrcngeaspercustomer: String,
    val smsmobileno: Any,
    val state: String,
    val telno: Any,
    val vat: Any,
    val volfactor: Int,
    val zipcode: String
)