package com.greensoft.greentranserpnative.ui.operation.inscan_detail_without_scanner.model

data class InScanDetailScannerModel(
    val airline: Any,
    val airlinecode: Any,
    val bookedpckgs: Double,
    val branchname: String,
    val custname: String,
    val custcode: String,
    val cnge: String,
    val cngr: String,
    val commandmessage: Any,
    val commandstatus: Int,
    var damage: Double,
    var damagereason: String? = "Select Reason",
    //var damagereason: String?,
    var damagereasoncode: String?,
    val despatchpckgs: Double,
    val despatchweight: Double,
    val destname: String,
    val grdt: String,
    val grno: String,
    val manifestdt: String,
    val manifestno: String,
    val manifesttime: String,
    val modecode: String,
    val modename: String,
    val orgcode: String,
    val origin: String,
    val mawbno: String,
    val pendingpckgs: Double,
    val pendingweight: Double,
    var receivedpckgs: Double,
    val receivedweight: Double,
    val remarks: String,
    val shortpckgs: Int,
    val sno: Int,
    val tostation: String
)