package com.greensoft.greentranserpnative.ui.operation.inscan_detail_without_scanner.model

data class InScanDetailModel(
    val airline: String,
    val airlinecode: String,
    val bookedpckgs: Double,
    val branchname: String,
    val cnge: String,
    val cngr: String,
    val commandmessage: Any,
    val commandstatus: Int,
    val damage: Double,
    val damagereason: Any,
    val despatchpckgs: Double,
    val despatchweight: Double,
    val destname: String,
    val grdt: String,
    val grno: String,
    val manifestdt: String,
    val manifestno: String,
    val manifesttime: String,
    val modecode: String,
    val modename: String,
    val orgcode: String,
    val origin: String,
    val pendingpckgs: Double,
    val pendingweight: Double,
    val receivedpckgs: Double,
    val receivedweight: Double,
    val remarks: String,
    val shortpckgs: Int,
    val sno: Int,
    val tostation: String
)